# TensorFlow Basics-1
## Constants, sessions, operations, and placeholders

** Import TensorFlow library**

In [ ]:
import tensorflow as tf

### Simple constants

In [3]:
hello = tf.constant('Hello World')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
x = tf.constant(100)

In [6]:
type(x)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
print(x)

Tensor("Const_1:0", shape=(), dtype=int32)


### Running Sessions

A Session object encapsulates the environment in which Operation objects are executed, and Tensor objects are evaluated.

In [9]:
sess = tf.Session()

In [10]:
# 'Run' method
sess.run(hello)

b'Hello World'

In [11]:
sess.run(x)

100

In [12]:
type(sess.run(hello))

bytes

In [13]:
type(sess.run(x))

numpy.int32

### Operations

In [21]:
x = tf.constant(3)
y = tf.constant(5)

In [22]:
with tf.Session() as sess:
    print('Operations with Constants\n'+'-'*30)
    print('Addition:',sess.run(x+y))
    print('Subtraction:',sess.run(x-y))
    print('Multiplication:',sess.run(x*y))
    print('Division:',sess.run(x/y))
    print('Exponentiation:',sess.run(x**y))

Operations with Constants
------------------------------
Addition: 8
Subtraction: -2
Multiplication: 15
Division: 0.6
Exponentiation: 243


** Sessions can be closed any time**

In [ ]:
x = tf.constant(5)
y = tf.constant(10)
sess=tf.Session()
print("x and y added together:", sess.run(x+y))
sess.close()

** Now, if one tries to run a command on the session, it will generate an error**

In [75]:
print("x and y multiplied together:", sess.run(x*y))

RuntimeError: Attempted to use a closed Session.

** But the constants are in the memory. One just has to open a session and evaluate**

In [76]:
sess = tf.Session()
print("x and y multiplied together:", sess.run(x*y))

x and y multiplied together: 50


### Placeholders

You may not always have the constants right away, and you may be waiting for a constant to appear after a cycle of operations. tf.placeholder is a tool for this.

**Important**: This tensor will produce an error if evaluated. Its value must be fed using the `feed_dict` optional argument to `Session.run()`,
`Tensor.eval()`, or `Operation.run()`. For example, for a placeholder of a matrix of floating point numbers:

    x = tf.placeholder(tf.float32, shape=(1024, 1024))

In [27]:
x = tf.placeholder(tf.int32)
y = tf.placeholder(tf.int32)
print("Here is x:",x)
print("Type of x:",type(x))

Here is x: Tensor("Placeholder_8:0", dtype=int32)
Type of x: <class 'tensorflow.python.framework.ops.Tensor'>


### Using built-in operations with placeholders

In [29]:
add = tf.add(x,y)
sub = tf.subtract(x,y)
mul = tf.multiply(x,y)
div = tf.divide(x,y)

** Defining the dictionary with variables**.

Note the definition of key is not with a string but with the variable itself

In [30]:
d = {x:20,y:30}

In [32]:
with tf.Session() as sess:
    print('Operations with Constants\n'+'-'*30)
    print('Addition:',sess.run(add,feed_dict=d))
    print('Subtraction:',sess.run(sub,feed_dict=d))
    print('Multiplication:',sess.run(mul,feed_dict=d))
    print('Division:',sess.run(div,feed_dict=d))

Operations with Constants
------------------------------
Addition: 50
Subtraction: -10
Multiplication: 600
Division: 0.666666666667


### Example of a more complex operation with matrices

In [34]:
import numpy as np
# Make sure to use floats here, int64 will cause an error.
a = np.array([5.0,4.0]).reshape(1,2)
b = np.array([2.0,3.0]).reshape(2,1)

In [35]:
a

array([[ 5.,  4.]])

In [36]:
b

array([[ 2.],
       [ 3.]])

In [37]:
mat1 = tf.constant(a)
mat2 = tf.constant(b)

** The matrix multiplication operation**

In [38]:
matrix_multi = tf.matmul(mat1,mat2)

** Now, run the operation to evaluate**

In [60]:
with tf.Session() as sess:
    result = sess.run(matrix_multi)
print(result)
print(type(result))

[[ 22.]]
<class 'numpy.ndarray'>


** One can also define the matrix directly with constant method**

In [49]:
a = tf.constant([1.0, 2.0, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9.0, 10, 11, 12], shape=[3, 2])

In [50]:
a

<tf.Tensor 'Const_10:0' shape=(2, 3) dtype=float32>

In [51]:
b

<tf.Tensor 'Const_11:0' shape=(3, 2) dtype=float32>

In [52]:
c = tf.matmul(a, b)

** Note 'c' is not yet run!**

In [61]:
print(c)

Tensor("MatMul_2:0", shape=(2, 2), dtype=float32)


** Initiate a session and evaluate 'c' by 'run' method**

In [66]:
sess = tf.Session()
sess.run(c)

array([[  58.,   64.],
       [ 139.,  154.]], dtype=float32)

In [69]:
with tf.Session() as sess:
    print('Determinant of the resultant matrix\n'+'-'*40)
    print(sess.run(tf.matrix_determinant(c)))
    print('\nInverse of the resultant matrix\n'+'-'*40)
    print(sess.run(tf.matrix_inverse(c)))

Determinant of the resultant matrix
----------------------------------------
36.0003

Inverse of the resultant matrix
----------------------------------------
[[ 4.27774096 -1.77776229]
 [-3.86107755  1.6110971 ]]


# Great job! See you soon :)