# TensorFlow Basics
# Constants, sessions, operations, placeholders, variables, graphs

### Import TensorFlow library

In [17]:
import tensorflow as tf
print(tf.__version__)

1.2.1


## Simple constants

In [2]:
hello = tf.constant('Hello World')

In [3]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [4]:
x = tf.constant(100)

In [5]:
type(x)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
print(x)

Tensor("Const_1:0", shape=(), dtype=int32)


### Running Sessions

A Session object encapsulates the environment in which Operation objects are executed, and Tensor objects are evaluated.

In [8]:
sess = tf.Session()

In [9]:
# 'Run' method
sess.run(hello)

b'Hello World'

In [10]:
sess.run(x)

100

In [11]:
type(sess.run(hello))

bytes

In [12]:
type(sess.run(x))

numpy.int32

## Operations

In [13]:
x = tf.constant(3)
y = tf.constant(5)

In [14]:
with tf.Session() as sess:
    print('Operations with Constants\n'+'-'*30)
    print('Addition:',sess.run(x+y))
    print('Subtraction:',sess.run(x-y))
    print('Multiplication:',sess.run(x*y))
    print('Division:',sess.run(x/y))
    print('Exponentiation:',sess.run(x**y))

Operations with Constants
------------------------------
Addition: 8
Subtraction: -2
Multiplication: 15
Division: 0.6
Exponentiation: 243


** Sessions can be closed any time**

In [15]:
x = tf.constant(5)
y = tf.constant(10)
sess=tf.Session()
print("x and y added together:", sess.run(x+y))
sess.close()

x and y added together: 15


** Now, if one tries to run a command on the session, it will generate an error**

In [16]:
print("x and y multiplied together:", sess.run(x*y))

RuntimeError: Attempted to use a closed Session.

** But the constants are in the memory. One just has to open a session and evaluate**

In [ ]:
sess = tf.Session()
print("x and y multiplied together:", sess.run(x*y))

### Interactive Session
Useful only for notebook session

In [19]:
const = tf.constant(10)
# Filling matrix
fill_mat = tf.fill((4,4),10)
# Zero matrix
myzeros = tf.zeros((4,4))
# Ones matrix
myones = tf.ones((4,4))
# Random (normal distribution) matrix
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)
# Random (uniform distribution) matrix
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

**Put these operations into a list**

In [20]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [40]:
c1=my_ops[0].name
c1=str(c1).split('_')[0]

In [41]:
c1

'Const'

In [21]:
# Only run this cell once!
sess = tf.InteractiveSession()

**Now run the elements of the list i.e. operations in a loop**

In [42]:
for op in my_ops:
    print ((str(op.name)).split('_')[0])
    print("-----------------------")
    print(op.eval())
    print('\n')

Const
-----------------------
10


Fill:0
-----------------------
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


zeros:0
-----------------------
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


ones:0
-----------------------
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


random
-----------------------
[[ 0.81641686  0.11190299 -0.89813626 -0.44156933]
 [ 0.4935073   0.52070194  0.00705446  0.55898827]
 [ 0.09099887  0.71810746 -0.21491098  0.10110044]
 [ 0.13559905 -0.04180802  1.27461052 -0.58999604]]


random
-----------------------
[[ 0.84797645  0.99187529  0.62942517  0.40425634]
 [ 0.77173674  0.93519151  0.8975234   0.81465852]
 [ 0.12147546  0.40328979  0.75558794  0.79052985]
 [ 0.43347394  0.87494993  0.48741555  0.69637501]]




## Placeholders

You may not always have the constants right away, and you may be waiting for a constant to appear after a cycle of operations. tf.placeholder is a tool for this.

**Important**: This tensor will produce an error if evaluated. Its value must be fed using the `feed_dict` optional argument to `Session.run()`,
`Tensor.eval()`, or `Operation.run()`. For example, for a placeholder of a matrix of floating point numbers:

    x = tf.placeholder(tf.float32, shape=(1024, 1024))

In [67]:
x = tf.placeholder(tf.int32)
y = tf.placeholder(tf.int32)
print("Here is x:",x)
print("Type of x:",type(x))

Here is x: Tensor("Placeholder:0", dtype=int32)
Type of x: <class 'tensorflow.python.framework.ops.Tensor'>


### Using built-in operations with placeholders

In [68]:
add = tf.add(x,y)
sub = tf.subtract(x,y)
mul = tf.multiply(x,y)
div = tf.divide(x,y)

** Defining the dictionary with variables**.

Note the definition of key is not with a string but with the variable itself

In [69]:
d = {x:20,y:30}

In [70]:
with tf.Session() as sess:
    print('Operations with Constants\n'+'-'*30)
    print('Addition:',sess.run(add,feed_dict=d))
    print('Subtraction:',sess.run(sub,feed_dict=d))
    print('Multiplication:',sess.run(mul,feed_dict=d))
    print('Division:',sess.run(div,feed_dict=d))

Operations with Constants
------------------------------
Addition: 50
Subtraction: -10
Multiplication: 600
Division: 0.666666666667


### Example of a more complex operation with matrices

In [43]:
import numpy as np
# Make sure to use floats here, int64 will cause an error.
a = np.array([5.0,4.0]).reshape(1,2)
b = np.array([2.0,3.0]).reshape(2,1)

In [44]:
a

array([[ 5.,  4.]])

In [45]:
b

array([[ 2.],
       [ 3.]])

In [47]:
mat1 = tf.constant(a)
mat2 = tf.constant(b)

### Matrix multiplication

In [48]:
matrix_multi = tf.matmul(mat2,mat1)

** Now, run the operation to evaluate**

In [49]:
with tf.Session() as sess:
    result = sess.run(matrix_multi)
print(result)
print(type(result))

[[ 10.   8.]
 [ 15.  12.]]
<class 'numpy.ndarray'>


** One can also define the matrix directly with constant method**

In [50]:
a = tf.constant([1.0, 2.0, 3, 4, 5, 6], shape=[2, 3])
b = tf.constant([7, 8, 9.0, 10, 11, 12], shape=[3, 2])

In [51]:
a

<tf.Tensor 'Const_11:0' shape=(2, 3) dtype=float32>

In [52]:
b

<tf.Tensor 'Const_12:0' shape=(3, 2) dtype=float32>

In [53]:
c = tf.matmul(a, b)

** Note 'c' is not yet run!**

In [54]:
print(c)

Tensor("MatMul_1:0", shape=(2, 2), dtype=float32)


** Initiate a session and evaluate 'c' by 'run' method**

In [55]:
sess = tf.Session()
sess.run(c)

array([[  58.,   64.],
       [ 139.,  154.]], dtype=float32)

In [56]:
with tf.Session() as sess:
    print('Determinant of the resultant matrix\n'+'-'*40)
    print(sess.run(tf.matrix_determinant(c)))
    print('\nInverse of the resultant matrix\n'+'-'*40)
    print(sess.run(tf.matrix_inverse(c)))

Determinant of the resultant matrix
----------------------------------------
36.0003

Inverse of the resultant matrix
----------------------------------------
[[ 4.27774096 -1.77776229]
 [-3.86107755  1.6110971 ]]


## Variables

In [71]:
my_tensor = tf.random_uniform((4,4),0,1)
my_var = tf.Variable(initial_value=my_tensor)

In [72]:
print(my_var)

<tf.Variable 'Variable_1:0' shape=(4, 4) dtype=float32_ref>


** Global variables must be initialized**

In [73]:
# This line is really important, it is easy to forget!
init = tf.global_variables_initializer()

In [74]:
init.run()

In [78]:
my_var.eval()

array([[ 0.99665356,  0.95176709,  0.74161661,  0.73446476],
       [ 0.29746151,  0.47238851,  0.91268456,  0.75048494],
       [ 0.7408855 ,  0.13339961,  0.77775478,  0.07073438],
       [ 0.96607578,  0.7623415 ,  0.06165969,  0.76032197]], dtype=float32)

## Graphs

When we start TF, a default graph is always created

In [80]:
print(tf.get_default_graph())

### Setting a user-defined graph as default

In [81]:
graph_one = tf.get_default_graph()
graph_two = tf.Graph()

In [82]:
graph_one is tf.get_default_graph()

True

In [83]:
graph_two is tf.get_default_graph()

False

In [84]:
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())

True


In [85]:
graph_two is tf.get_default_graph()

False